config/routes.rb
Rails.application.routes.draw do
  # resources :dogs
  resources :tickets

  get 'spa_tickets', to: 'tickets#spa_index', as: 'spa_tickets'
  post 'tickets/spa_create', to: 'tickets#spa_create', as: 'spa_create_ticket'
  post 'tickets/:id/spa_edit', to: 'tickets#spa_edit', as: 'spa_edit_ticket'
  post 'tickets/:id/spa_cancel', to: 'tickets#spa_cancel', as: 'spa_cancel_ticket'
  patch 'tickets/:id/spa_update', to: 'tickets#spa_update', as: 'spa_update_ticket'
  delete 'tickets/:id/spa_destroy', to: 'tickets#spa_destroy', as: 'spa_destroy_ticket'

  get 'pages/home'
  get 'pages/about'
  get 'pages/async_turbo_frame'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # get 'spa_tickets', to: 'tickets#spa_index'
  # post 'create_spa_ticket', to: 'tickets#spa_create'

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  include TicketBroadcasts
  validates :title, presence: true, length: { minimum: 1, maximum: 50 }

  after_create_commit lambda{ broadcast_create_to_listeners }
  after_update_commit lambda{ broadcast_update_to_listeners }
  after_destroy_commit lambda{ broadcast_destroy_to_listeners }

  # broadcasts
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy spa_update spa_edit spa_cancel spa_destroy]
  skip_before_action :verify_authenticity_token, only: [:spa_cancel]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.order("created_at DESC").all
    @ticket = Ticket.new
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    respond_to do |format|
      format.html { render :edit }
    end
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #----------------------------------------------------------
  #-------------------  SPA ACTIONS -------------------------
  #----------------------------------------------------------

  # GET /spa_tickets
  def spa_index
    @tickets = Ticket.order("created_at DESC").all
    @ticket = Ticket.new
  end

  # POST /tickets/1/spa_edit
  def spa_edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: []
        @ticket.broadcast_edit_to_listeners
      end
    end
  end

  # POST /tickets/1/spa_cancel
  def spa_cancel
    respond_to do |format|
      # format.turbo_stream
      format.html do
        head :no_content
        @ticket.broadcast_edit_cancel_to_listeners
      end
    end
  end

  # POST /spa_tickets
  def spa_create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.turbo_stream do
          render turbo_stream: []
          # @ticket.broadcast_create_to_listeners
        end
      else
      end
    end
  end

  # PATCH /tickets/1/spa_update
  def spa_update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.turbo_stream do
          render turbo_stream: []
          # @ticket.broadcast_update_to_listeners
        end
      else
      end
    end
  end

  # DELETE /tickets/1/spa_destroy
  def spa_destroy
    @ticket.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: []
        # @ticket.broadcast_destroy_to_listeners
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :problem, :fixed)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.slim
= form_with(model: ticket) do |form|
  - if ticket.errors.any?
    div style="color: red"
      h2 = "#{pluralize(ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - ticket.errors.each do |error|
          li = error.full_message

  div style="display: inline-block"
    = form.text_field :title, class: "form-control", placeholder: "title", style: "width: 300px"

  div style="display: inline-block"
    = form.text_field :problem, class: "form-control", placeholder: "problem", style: "width: 700px"

  div
    = form.submit

app/views/tickets/_spa_edit_form.html.slim
section.bg-light.my-1.p-1.rounded-2 id="ticket-#{ticket.id}"
  = form_with(model: ticket, url: spa_update_ticket_path(ticket)) do |form|
    - if ticket.errors.any?
      div style="color: red"
        h2 = "#{pluralize(ticket.errors.count, "error")} prohibited this ticket from being saved:"
        ul
          - ticket.errors.each do |error|
            li = error.full_message

    span.d-inline-flex.p-1.w-100.justify-content-between.align-items-center
      span.me-2 style="width:75px" => "Title:"
      = form.text_field :title, class: "form-control", placeholder: "title"

    span.d-inline-flex.p-1.w-100.align-items-top
      span.me-2 style="width:75px" => "Problem:"
      = form.text_area :problem, sizex: '50x10', class: "form-control", placeholder: "problem", style: "height:200px"

    span.d-inline-flex.w-100.justify-content-center
      div.text-center.borderx.border-danger style="width:300px"
        span.d-inline-block.m-1
          = form.button nil, class: "btn btn-sm btn-success my-1" do
            i.bi.bi-check-lg
            span =< "Update"
        span.d-inline-block.m-1
          = button_to spa_cancel_ticket_path(ticket), method: :post, class: "btn btn-sm btn-primary my-1 d-inline-block" do
            i.bi.bi-x-lg
            span =< "Cancel"

app/views/tickets/_spa_new_form.html.slim
/ = form_with(model: ticket, url: spa_create_ticket_path, method: :post, id: "new-ticket-form") do |form|
/   - if ticket.errors.any?
/     div style="color: red"
/       h2 = "#{pluralize(ticket.errors.count, "error")} prohibited this ticket from being saved:"
/       ul
/         - ticket.errors.each do |error|
/           li = error.full_message

/   div
/     = form.label :title, style: "display: block"
/     = form.text_field :title

/   div
/     = form.label :problem, style: "display: block"
/     = form.text_area :problem

/   / div
/   /   = form.label :fixed, style: "display: block"
/   /   = form.check_box :fixed

/   div
/     = form.submit "Create a Ticket", class: "btn btn-success"


section#new-ticket-form.my-1.p-1.rounded-2.bg-light stylex="background-color: lightgreen"
  = form_with(model: ticket, url: spa_create_ticket_path, method: :post) do |form|
    - if ticket.errors.any?
      div style="color: red"
        h2 = "#{pluralize(ticket.errors.count, "error")} prohibited this ticket from being saved:"
        ul
          - ticket.errors.each do |error|
            li = error.full_message

    span.d-inline-flex.p-1.w-100.justify-content-between.align-items-center
      span.me-2 style="width:75px" => "Title:"
      = form.text_field :title, class: "form-control"

    span.d-inline-flex.p-1.w-100.align-items-top
      span.me-2 style="width:75px" => "Problem:"
      = form.text_area :problem, sizex: '50x10', class: "form-control", style: "height:200px"

    span.d-inline-flex.w-100.justify-content-center
      div.text-center.borderx.border-danger style="width:300px"
        span.d-inline-block.m-1
          = form.button nil, class: "btn btn-sm btn-success my-1" do
            i.bi.bi-check-lg
            span =< "Create a Ticket"

app/views/tickets/_spa_ticket.html.slim
label.list-group-item id="ticket-#{ticket.id}"
  / see list groups https://getbootstrap.com/docs/5.0/components/list-group/

  div.d-flex.w-100.justify-content-between.align-items-center
    div
      input.form-check-input.me-1 type="checkbox" value=true aria-label="..."
      span.h5.text-primary =< ticket.title
      p.mb-1.ms-4 = ticket.problem
      small.ms-4.text-muted = "ID #{ticket.id}, Fixed: #{ticket.fixed ? 'Yes' : 'No'}"

    div.for-flex-box
      div.text-end.borderx.borderx-danger style="width:70px"
        = button_to spa_edit_ticket_path(ticket), method: :post, class: "btn btn-sm btn-primary mx-1 my-1" do
          i.bi.bi-pencil
          / span =< "Edit"
        = button_to spa_destroy_ticket_path(ticket), method: :delete, class: "btn btn-sm btn-danger mx-1 my-1" do
          i.bi.bi-trash
          / span =< "Destroy"

app/views/tickets/_ticket.html.slim
div id="ticket-#{ticket.id}"
  .container style="background:orange;margin:5px 0; padding:10px; border-radius: 10px"

    / div style="float:right"
      div style="display:inline-block;"
        = button_to "Edit", edit_ticket_path(ticket), method: :post, class: "btn btn-sm btn-primary mx-2 my-2"
      div style="display:inline-block;"
        = button_to "Destroy", ticket, method: :delete, class: "btn btn-sm btn-danger mx-2 my-2"

    span style="margin:5px;color:darkblue;font-weight:bold"
      = ticket.title
    span
      =< ticket.problem
    p style="margin:5px;floatx:right"
      strong Fixed:
      =< ticket.fixed ? 'Yes' : 'No'
    p style="margin:5px"
      strong ID:
      =< ticket.id

app/views/tickets/edit.html.slim
.container style="background:lightgreen; padding:10px; border-radius:10px"
  h1 Editing ticket sithout dog

  == render "form", ticket: @ticket

  br

  div
    => link_to "Show this ticket", @ticket
    '|
    =< link_to "Back to tickets", tickets_path

app/views/tickets/index.html.slim
p style="color: green"
  span#notice = notice

.container style="background:lightblue; padding:10px; border-radius:20px"
  h1 OLD Ticket Management

  #tickets-go-here
    - @tickets.each do |ticket|
      == render ticket
      p
        => link_to "Show this ticket", ticket
        '|
        =< link_to "Edit this ticket", edit_ticket_path(ticket)
        / = button_to "Delete", ticket, method: :delete

  = link_to "New ticket", new_ticket_path

app/views/tickets/new.html.slim
.container style="background:lightgreen; padding:10px; border-radius:20px"
  h1 New ticket

  == render "form", ticket: @ticket

  br

  div
    = link_to "Back to tickets", tickets_path

app/views/tickets/show.html.slim
p style="color: green"
  span#notice = notice

.container style="background:lightblue;padding:10px;"
  == render @ticket

  div
    => link_to "Edit this ticket", edit_ticket_path(@ticket)
    '|
    =< link_to "Back to tickets", tickets_path

    = button_to "Destroy this ticket", @ticket, method: :delete

app/views/tickets/spa_index.html.slim
= turbo_stream_from "ticket-listeners"

p style="color: green"
  span#notice = notice

.container style="background:lightblue; padding:10px; border-radius:20px"
  h1.text-sm-start.text-md-center.text-lg-end SPA Ticket Management

  == render "spa_new_form", ticket: @ticket
  br

  #tickets-go-here.list-group
    - @tickets.each do |ticket|
      / == render ticket
      == render 'spa_ticket', ticket: ticket