config/routes.rb
Rails.application.routes.draw do
  # resources :dogs
  resources :tickets

  get 'spa_tickets', to: 'tickets#spa_index', as: 'spa_tickets'
  post 'tickets/spa_create', to: 'tickets#spa_create', as: 'spa_create_ticket'
  post 'tickets/:id/spa_edit', to: 'tickets#spa_edit', as: 'spa_edit_ticket'
  post 'tickets/:id/spa_cancel', to: 'tickets#spa_cancel', as: 'spa_cancel_ticket'
  patch 'tickets/:id/spa_update', to: 'tickets#spa_update', as: 'spa_update_ticket'
  delete 'tickets/:id/spa_destroy', to: 'tickets#spa_destroy', as: 'spa_destroy_ticket'

  get 'pages/home'
  get 'pages/about'
  get 'pages/async_turbo_frame'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"

  # get 'spa_tickets', to: 'tickets#spa_index'
  # post 'create_spa_ticket', to: 'tickets#spa_create'

end

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-expand-lg navbar-light bg-light"
  div class="container-fluid"
    a class="navbar-brand" href="#{root_path}"
      = "TicketBuster"
    button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span class="navbar-toggler-icon"

    div class="collapse navbar-collapse" id="navbarSupportedContent"
      ul class="navbar-nav me-auto mb-2 mb-lg-0"
        li class="nav-item"
          = link_to "Home", root_path, aria_current: "page", class: "nav-link"
        li class="nav-item"
          = link_to "About", pages_about_path, aria_current: "page", class: "nav-link"
        li class="nav-item"
          = link_to "OLD Tickets", tickets_path, aria_current: "page", class: "nav-link"
        li class="nav-item"
          = link_to "SPA Tickets", spa_tickets_path, aria_current: "page", class: "nav-link"

app/views/layouts/_ticket_notice.html.slim
div#ticket-notice
  hr
  p style="color: green"
    = notice
  hr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <%
=begin%>
 <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
<%
=end%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <%= Time.zone.now.to_s %>
      <%= render partial: "layouts/ticket_notice", locals: {notice: "notice shows here"} %>
      <%= yield %>
    </main>
  </body>
</html>